---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-task-deployment
  labels:
    app: debug-task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-task-app
  template:
    metadata:
      labels:
        app: debug-task-app
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: debug-task-pvc
              mountPath: /uploads
          livenessProbe:
            httpGet:
              path: /nginx/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
        - name: app
          image: vepl/alpacked-test-task
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: debug-task-pvc
              mountPath: /app/data
            - name: debug-task-pvc
              mountPath: /uploads
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: debug-task-pvc
          persistentVolumeClaim:
            claimName: debug-task-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: debug-task-app
data:
  default.conf: |
    server {
        listen 8081;
 
        location / {
            proxy_pass http://localhost:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
 
        location /uploads {
            alias /uploads;
            autoindex on;
            index off;
        }

        location /nginx/health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }

    }
---
apiVersion: v1
kind: Service
metadata:
  name: debug-task-service
spec:
  selector:
    app: debug-task-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debug-task-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
